const countries = [
	"afghanistan", "kabul",
	"albania",
	"algeria", "algiers",
	"andorra", "andorra la vella",
	"angola", "launda",
	"anguilla",
	"antarctica",
	"antigua",
    "antigua and barbuda",
	"argentina", "buenos aries",
	"armenia",
	"australia", "canberra", "sydney", "perth",
	"austria", "vienna",
	"azerbaijan",
	"bahamas",
	"bahrain",
	"bangladesh", "dhaka",
	"barbados",
	"belarus", "minsk",
	"belgium",  "brussels",
	"belize", 
	"benin",
	"bermuda",
	"bhutan", "thimpu",
	"bolivia", "la paz",
	"bonaire", 
	"bosnia and herzegovina", "sarajevo",
	"botswana",
	"bouvet island",                                                                                        
	"brazil", "brasillia", "rio de janerio", 
	"british indian ocean territory",
	"brunei",
	"bulgaria", "sophia",
	"burkina faso",
	"burundi", 
	"cabo verde",
	"cambodia", "phnom penh",
	"cameroon", 
	"canada", "ottowa", "toronto",
	"cayman islands",
	"central african republic",
	"chad",
	"chile", "santiago",
	"china", "bejing", "shanghai", "guangzhou",
	"christmas island",
	"cocos island",
	"colombia", "bogota",
	"comoros",
	"democratic republic of congo", "khinshasa",
	"congo",
	"cook islands",
	"costa rica",
	"croatia",
	"cuba", "havana",
	"curacao",
	"cyprus",
	"czechia", "prague",
	"cote d'ivoire",
	"denmark", "kopenhagen", "copenhagen",
	"djibouti",
	"dominica",
	"dominican republic",
	"ecuador",
	"egypt", "cairo", "alexandria",
	"el salvador", "salvador",
	"equatorial guinea",
	"eriteria",
	"estonia", "talinn",
	"eswantini",
	"ethiopia", "addis ababa",
	"falkland islands",
	"faroe islands",
	"fiji",
	"finland", "helsinki",
	"france", "paris", "lyon", "marsielle",
	"french guiana",
	"french polynesia",
	"french southern territories",
	"gabon",
	"gambia",
	"georgia", "tbillisi",
	"germany", "berlin", "hamburg", "frankfurt", "munich",
	"ghana",
	"gibraltar",
	"greece", "athens", "thessaloniki",
	"greenland", "nuuk",
	"grenada",
	"guadeloupe",
	"guam",
	"guatemala",
	"guernsey",
	"guinea",
	"guinea bissau",
	"guyana",
	"haiti",
	"holy see",
    "vatican city", "vatican",
	"honduras",
	"hong kong",
	"hungary", "budapest",
	"iceland", 
	"india", "delhi", "mumbai", "chennai", "ahemdabad", "zirakpur", "gokak", "bangalore", "hyderabad", "bhuhaneswar",
    "indonesia", "jakarta",
	"iran", "tehran",
	"iraq", "baghdad",
	"ireland", "dublin",
	"isle of man",
	"israel", 
	"italy", "rome", "venice", "napels",
	"jamaica",
	"japan", "tokyo", "osaka",
	"jersey",
	"jordan", "amman",
	"kazakhstan", 
	"kenya", "nairobi",
	"kiribati",
	"north korea", "pyongyang",
	"south korea", "souel",
	"kuwait", "kuwait city",
	"kyrgyzstan",
	"lao",
	"latvia",
	"lebanon", "beirut",
	"lesotho",
	"liberia",
	"libya", "tripoli",
	"liechtenstein", "vaduz",
	"lithuania", "vilnus",
	"luxembourg", "luxembourg city",
	"macao",
	"madagascar",
	"malawi",
	"malaysia", "kuala lumpur",
	"maldives", "male",
	"mali",
	"malta",
	"marshall islands",
	"martinique",
	"mauritana",
	"mauritius",
	"mayotte",
	"mexico", "mexico city",
	"micronesia",
	"moldova",
	"monaco", "monaco city",
	"mongolia", "ulaanbatar",
	"montenegro",
	"montserrat",
	"morocco",
	"mozambique",
	"myanmar",
	"namibia",
	"nauru",
	"nepal",
	"netherlands", "amsterdam", "rotterdam",
	"new caledonia",
	"new zealand", "auckland", "wellington",
	"nicaragua",
	"niger",
	"nigeria",
	"niue",
	"norfolk island",
	"northern mariana islands",
    "north macedonia",
	"norway", "oslo",
	"oman", "muscat",
	"pakistan", "lahore", "islamabad", "karachi",
	"palau",
	"palestine",
	"panama",
	"papua new guinea",
	"paraguay",
	"peru",
	"philippines",
	"pitcairn",
	"poland", "warsaw",
	"portugal", "lisbon",
	"puerto rico",
	"qatar",
	"north macedonia", "macedonia",
	"romania", "bucharest",
	"russia", "moscow", "saint petersburg", "volgograd",
	"rwanda",
	"reunion",
	"saint barthelemy",
	"saint helena",
	"saint kitts and nevis",
	"saint lucia",
	"saint martin",
	"saint pierre",
	"saint vincent and the grenadines",
	"samoa",
	"san marino",
	"sao tome and principe",
	"saudi arabia", "riyadh", "mecca",
	"senegal",
	"serbia",
	"seychelles",
	"sierra leone",
	"singapore",
	"sint maarten",
	"slovakia",
	"slovenia",
	"solomon islands",
    "somalia",
    "south africa", "petoria", "cape town", "johanesburg",
    "south georgia and the south sandwich islands",
    "south sudan",
    "spain",
    "sri lanka",
    "sudan",
    "suriname",
    "svalbard",
    "sweden",
    "switzerland",
    "syria",
    "taiwan",
    "tajikistan",
    "tanzania",
    "thailand",
    "timor leste",
    "togo",
    "tokelau",
    "tonga",
    "trinidad and tobago",
    "tunisia",
    "turkey",
    "turkmenistan",
    "turks and caicos islands",
    "tuvalu",
    "uganda",
    "ukraine",
    "united arab emirates",
    "united kingdom",
    "uk",
    "usa",
    "united states of america",
    "uruguay",
    "uzbekistan",
    "vanuatu",
    "venezuela",
    "vietnam",
    "virgin islands",
    "wallis and futuna",
    "western sahara",
    "yemen",
    "zambia",
    "zimbabwe",
    "aland islands",
	"south america",
	"africa",
	"asia",
	"antartica",
	"north america", 
	"europe",
	"australia",
	"indian ocean",
	"pacific ocecan", 
	"artic ocean",
	"atlantic ocean",
	"caspian sea",
	"black sea",
	"gulf of mexico",
	"great lakes",
	"southern ocean"
]

const alphabet = [
   'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'p', 'r', 's', 't', 'u', 'v'
]

const inputField = document.querySelector('.input')
const letterDisplay = document.querySelector('.letter')
const statusDisplay = document.querySelector('.status')
const choosenCountryName = document.querySelector('.country-name')
const guessedCountriesDisplay = document.querySelector('.countries-guessed')

let countriesGuessed = JSON.parse(localStorage.getItem('countriesGuessed'))
guessedCountriesDisplay.innerText = countriesGuessed

let letter = 's'

inputField.addEventListener('input', () => {
    enteredCountryName = inputField.value.toLowerCase()
    if (enteredCountryName[0] == letter && countries.includes(enteredCountryName)) {
        const letter = alphabet[Math.floor(Math.random() * alphabet.length)]
        letterDisplay.innerText = letter
        inputField.value = '' 
        countriesGuessed += 1
        localStorage.setItem('countriesGuessed', JSON.stringify(countriesGuessed))
        guessedCountriesDisplay.innerText = countriesGuessed
    }
});


